version: '3'
services:
    plugin:
        build: 
            context: .
        environment:
        - PLUGIN_KIND=apply
        - PLUGIN_CLUSTER=k8s.dev.movio.co
        - PLUGIN_AUTH_MODE=aws-iam-authenticator
        - PLUGIN_K8S_FILE=scripts/configmap.yml
        - PLUGIN_DIR=/bin/scripts,/bin/scripts
        - PLUGIN_SERVER_URL_K8S=https://api.k8s.dev.movio.co
        - PLUGIN_ROLE=arn:aws:iam::650454640207:role/DroneK8sRole
        - DRONE_REPO_OWNER=andrei
        - DRONE_REPO_NAME=movio