version: '3'
services:
    plugin:
        build: 
            context: .
        environment:
        - PLUGIN_KIND=deployment
        - PLUGIN_DEPLOYMENT=api-web 
        - PLUGIN_DAEMONSET=api-web 
        - PLUGIN_USER=razorpay 
        - PLUGIN_NAMESPACE=default 
        - PLUGIN_CLUSTER=kluster-api,movio-dev
        - PLUGIN_AUTH_MODE=aws-iam-authenticator
        - PLUGIN_TAG=latest
        - PLUGIN_REPO=octocat/hello-world 
        - SERVER_URL_KLUSTERAPI=https://api.k8s.dev.movio.co.:443